export const INITIAL_STUDENTS = [
  // CLASS 1 BOYS (9 Students)
  { id: 'c1-b-1', admissionNo: 'AD-1001', name: 'Muhammed Rahil. K', classNum: 'Class 1', category: 'Kiddies', gender: 'Boys', group: 'GRP-A', rollNo: 1, isLeader: false, chestNo: 207, status: 'active' },
  { id: 'c1-b-6', admissionNo: 'AD-1006', name: 'MUHAMMED DHILSHAN V', classNum: 'Class 1', category: 'Kiddies', gender: 'Boys', group: 'GRP-B', rollNo: 6, isLeader: false, chestNo: 107, status: 'active' },
  { id: 'c1-b-7', admissionNo: 'AD-1007', name: 'MUHAMMAD SWALIH . K', classNum: 'Class 1', category: 'Kiddies', gender: 'Boys', group: 'GRP-C', rollNo: 7, isLeader: false, chestNo: 307, status: 'active' },
  { id: 'c1-b-8', admissionNo: 'AD-1008', name: 'ARSHAD YASEEN.K', classNum: 'Class 1', category: 'Kiddies', gender: 'Boys', group: 'GRP-A', rollNo: 8, isLeader: false, chestNo: 208, status: 'active' },
  { id: 'c1-b-9', admissionNo: 'AD-1009', name: 'MUHAMMED SAHAD SHAN K', classNum: 'Class 1', category: 'Kiddies', gender: 'Boys', group: 'GRP-B', rollNo: 9, isLeader: false, chestNo: 108, status: 'active' },
  { id: 'c1-b-10', admissionNo: 'AD-1010', name: 'MUHAMMED MUDHASSIR. K', classNum: 'Class 1', category: 'Kiddies', gender: 'Boys', group: 'GRP-C', rollNo: 10, isLeader: false, chestNo: 308, status: 'active' },
  { id: 'c1-b-11', admissionNo: 'AD-1011', name: 'MUHAMMED FAIZAN C', classNum: 'Class 1', category: 'Kiddies', gender: 'Boys', group: 'GRP-A', rollNo: 11, isLeader: false, chestNo: 209, status: 'active' },
  { id: 'c1-b-21', admissionNo: 'AD-1021', name: 'MUHAMMED RIYAN.K', classNum: 'Class 1', category: 'Kiddies', gender: 'Boys', group: 'GRP-B', rollNo: 21, isLeader: false, chestNo: 109, status: 'active' },
  { id: 'c1-b-22', admissionNo: 'AD-1022', name: 'NAZMIL M', classNum: 'Class 1', category: 'Kiddies', gender: 'Boys', group: 'GRP-C', rollNo: 22, isLeader: false, chestNo: 309, status: 'active' },

  // CLASS 1 GIRLS (14 Students)
  { id: 'c1-g-2', admissionNo: 'AD-1002', name: 'Naja MK', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-A', rollNo: 2, isLeader: false, chestNo: 255, status: 'active' },
  { id: 'c1-g-3', admissionNo: 'AD-1003', name: 'Siya Fathima. V', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-B', rollNo: 3, isLeader: false, chestNo: 155, status: 'active' },
  { id: 'c1-g-4', admissionNo: 'AD-1004', name: 'Ayisha Ifsa. V', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-C', rollNo: 4, isLeader: false, chestNo: 355, status: 'active' },
  { id: 'c1-g-5', admissionNo: 'AD-1005', name: 'Ameena Fathima. K', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-A', rollNo: 5, isLeader: false, chestNo: 256, status: 'active' },
  { id: 'c1-g-12', admissionNo: 'AD-1012', name: 'LIYA NOORIN', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-B', rollNo: 12, isLeader: false, chestNo: 156, status: 'active' },
  { id: 'c1-g-13', admissionNo: 'AD-1013', name: 'FILSHA FATHIMA K', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-C', rollNo: 13, isLeader: false, chestNo: 356, status: 'active' },
  { id: 'c1-g-14', admissionNo: 'AD-1014', name: 'AIZA FATHIMA V', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-A', rollNo: 14, isLeader: false, chestNo: 257, status: 'active' },
  { id: 'c1-g-15', admissionNo: 'AD-1015', name: 'AYNA MEHRISH V', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-B', rollNo: 15, isLeader: false, chestNo: 157, status: 'active' },
  { id: 'c1-g-16', admissionNo: 'AD-1016', name: 'Shabana V', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-C', rollNo: 16, isLeader: false, chestNo: 357, status: 'active' },
  { id: 'c1-g-17', admissionNo: 'AD-1017', name: 'FATHIMA SINVA.MK', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-A', rollNo: 17, isLeader: false, chestNo: 258, status: 'active' },
  { id: 'c1-g-18', admissionNo: 'AD-1018', name: 'FATHIMA HAVVA K.P', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-B', rollNo: 18, isLeader: false, chestNo: 158, status: 'active' },
  { id: 'c1-g-19', admissionNo: 'AD-1019', name: 'AlNA FATHIMA.K', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-C', rollNo: 19, isLeader: false, chestNo: 358, status: 'active' },
  { id: 'c1-g-20', admissionNo: 'AD-1020', name: 'NAIZA FATHIMA V', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-A', rollNo: 20, isLeader: false, chestNo: 259, status: 'active' },
  { id: 'c1-g-23', admissionNo: 'AD-1023', name: 'FATHIMA SHANZA KP', classNum: 'Class 1', category: 'Kiddies', gender: 'Girls', group: 'GRP-B', rollNo: 23, isLeader: false, chestNo: 159, status: 'active' },

  // CLASS 2 BOYS (11 Students)
  { id: 'c2-b-1', admissionNo: 'AD-2001', name: 'Faizan Muhammed. V', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-A', rollNo: 1, isLeader: false, chestNo: 210, status: 'active' },
  { id: 'c2-b-2', admissionNo: 'AD-2002', name: 'Ayas Rahman. V', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-B', rollNo: 2, isLeader: false, chestNo: 110, status: 'active' },
  { id: 'c2-b-3', admissionNo: 'AD-2003', name: 'Muhammed Ashbal. C', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-C', rollNo: 3, isLeader: false, chestNo: 310, status: 'active' },
  { id: 'c2-b-4', admissionNo: 'AD-2004', name: 'Muhammed Faizan. V', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-A', rollNo: 4, isLeader: false, chestNo: 211, status: 'active' },
  { id: 'c2-b-5', admissionNo: 'AD-2005', name: 'Muhammed Anshid M', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-B', rollNo: 5, isLeader: false, chestNo: 111, status: 'active' },
  { id: 'c2-b-6', admissionNo: 'AD-2006', name: 'Muhammed Nasim. MK', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-C', rollNo: 6, isLeader: false, chestNo: 311, status: 'active' },
  { id: 'c2-b-7', admissionNo: 'AD-2007', name: 'Muhammed Shadin. NK', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-A', rollNo: 7, isLeader: false, chestNo: 212, status: 'active' },
  { id: 'c2-b-8', admissionNo: 'AD-2008', name: 'Raseen Muhammed. NK', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-B', rollNo: 8, isLeader: false, chestNo: 112, status: 'active' },
  { id: 'c2-b-9', admissionNo: 'AD-2009', name: 'Muhammed Lazin. C', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-C', rollNo: 9, isLeader: false, chestNo: 312, status: 'active' },
  { id: 'c2-b-10', admissionNo: 'AD-2010', name: 'Shazin Mahmood. NK', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-A', rollNo: 10, isLeader: false, chestNo: 213, status: 'active' },
  { id: 'c2-b-22', admissionNo: 'AD-2022', name: 'MUHAMMAD HISHAN. M', classNum: 'Class 2', category: 'Kiddies', gender: 'Boys', group: 'GRP-B', rollNo: 22, isLeader: false, chestNo: 113, status: 'active' },

  // CLASS 2 GIRLS (11 Students)
  { id: 'c2-g-11', admissionNo: 'AD-2011', name: 'Fathima Swalha. M', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-C', rollNo: 11, isLeader: false, chestNo: 359, status: 'active' },
  { id: 'c2-g-12', admissionNo: 'AD-2012', name: 'Ayisha Marjan. K', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-A', rollNo: 12, isLeader: false, chestNo: 260, status: 'active' },
  { id: 'c2-g-13', admissionNo: 'AD-2013', name: 'Aima Rafi. V', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-B', rollNo: 13, isLeader: false, chestNo: 160, status: 'active' },
  { id: 'c2-g-14', admissionNo: 'AD-2014', name: 'Fathima Rayya. M', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-C', rollNo: 14, isLeader: false, chestNo: 360, status: 'active' },
  { id: 'c2-g-15', admissionNo: 'AD-2015', name: 'Hina Fathima. M', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-A', rollNo: 15, isLeader: false, chestNo: 261, status: 'active' },
  { id: 'c2-g-16', admissionNo: 'AD-2016', name: 'Ayisha Emin V', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-B', rollNo: 16, isLeader: false, chestNo: 161, status: 'active' },
  { id: 'c2-g-17', admissionNo: 'AD-2017', name: 'Fathima Faiha. K', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-C', rollNo: 17, isLeader: false, chestNo: 361, status: 'active' },
  { id: 'c2-g-18', admissionNo: 'AD-2018', name: 'Dilna Fathima. V', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-A', rollNo: 18, isLeader: false, chestNo: 262, status: 'active' },
  { id: 'c2-g-19', admissionNo: 'AD-2019', name: 'Raisal Janna. V', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-B', rollNo: 19, isLeader: false, chestNo: 162, status: 'active' },
  { id: 'c2-g-20', admissionNo: 'AD-2020', name: 'Fathima Dilva. M', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-C', rollNo: 20, isLeader: false, chestNo: 362, status: 'active' },
  { id: 'c2-g-21', admissionNo: 'AD-2021', name: 'Jaza Mariyam. M', classNum: 'Class 2', category: 'Kiddies', gender: 'Girls', group: 'GRP-A', rollNo: 21, isLeader: false, chestNo: 263, status: 'active' },

  // CLASS 3 BOYS (9 Students)
  { id: 'c3-b-2', admissionNo: 'AD-3002', name: 'MUHAMMAD AHYAN.M', classNum: 'Class 3', category: 'Sub Junior', gender: 'Boys', group: 'GRP-C', rollNo: 2, isLeader: false, chestNo: 313, status: 'active' },
  { id: 'c3-b-3', admissionNo: 'AD-3003', name: 'MUHAMMED FAIZAN.K', classNum: 'Class 3', category: 'Sub Junior', gender: 'Boys', group: 'GRP-A', rollNo: 3, isLeader: false, chestNo: 214, status: 'active' },
  { id: 'c3-b-4', admissionNo: 'AD-3004', name: 'MUHAMMED MINHAJ.K.P', classNum: 'Class 3', category: 'Sub Junior', gender: 'Boys', group: 'GRP-B', rollNo: 4, isLeader: false, chestNo: 114, status: 'active' },
  { id: 'c3-b-5', admissionNo: 'AD-3005', name: 'MUHAMMED RAYAN.M', classNum: 'Class 3', category: 'Sub Junior', gender: 'Boys', group: 'GRP-C', rollNo: 5, isLeader: false, chestNo: 314, status: 'active' },
  { id: 'c3-b-6', admissionNo: 'AD-3006', name: 'MUHAMMED RIFNAS.K', classNum: 'Class 3', category: 'Sub Junior', gender: 'Boys', group: 'GRP-A', rollNo: 6, isLeader: false, chestNo: 215, status: 'active' },
  { id: 'c3-b-7', admissionNo: 'AD-3007', name: 'MUHAMMED ZAYAN K', classNum: 'Class 3', category: 'Sub Junior', gender: 'Boys', group: 'GRP-B', rollNo: 7, isLeader: false, chestNo: 115, status: 'active' },
  { id: 'c3-b-16', admissionNo: 'AD-3016', name: 'MUHAMMED FIRNASUDEEN BC', classNum: 'Class 3', category: 'Sub Junior', gender: 'Boys', group: 'GRP-C', rollNo: 16, isLeader: false, chestNo: 315, status: 'active' },
  { id: 'c3-b-17', admissionNo: 'AD-3017', name: 'SHAZIN MUHAMMED NK', classNum: 'Class 3', category: 'Sub Junior', gender: 'Boys', group: 'GRP-A', rollNo: 17, isLeader: false, chestNo: 216, status: 'active' },
  { id: 'c3-b-20', admissionNo: 'AD-3020', name: 'MUHAMMED SWALIH. M', classNum: 'Class 3', category: 'Sub Junior', gender: 'Boys', group: 'GRP-B', rollNo: 20, isLeader: false, chestNo: 116, status: 'active' },

  // CLASS 3 GIRLS (11 Students)
  { id: 'c3-g-1', admissionNo: 'AD-3001', name: 'FILZA FATHIMA. M', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-B', rollNo: 1, isLeader: false, chestNo: 163, status: 'active' },
  { id: 'c3-g-8', admissionNo: 'AD-3008', name: 'AIFA MEHARIN V', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-C', rollNo: 8, isLeader: false, chestNo: 363, status: 'active' },
  { id: 'c3-g-9', admissionNo: 'AD-3009', name: 'FATHIMA RIFKHA KP', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-A', rollNo: 9, isLeader: false, chestNo: 264, status: 'active' },
  { id: 'c3-g-10', admissionNo: 'AD-3010', name: 'FATHIMA FAHMA M', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-B', rollNo: 10, isLeader: false, chestNo: 164, status: 'active' },
  { id: 'c3-g-11', admissionNo: 'AD-3011', name: 'SHAHDHA FATHIMA K', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-C', rollNo: 11, isLeader: false, chestNo: 364, status: 'active' },
  { id: 'c3-g-12', admissionNo: 'AD-3012', name: 'RANA FATHIMA K', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-A', rollNo: 12, isLeader: false, chestNo: 265, status: 'active' },
  { id: 'c3-g-13', admissionNo: 'AD-3013', name: 'RAYA FATHIMA K', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-B', rollNo: 13, isLeader: false, chestNo: 165, status: 'active' },
  { id: 'c3-g-14', admissionNo: 'AD-3014', name: 'FATHIMA HENNA M', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-C', rollNo: 14, isLeader: false, chestNo: 365, status: 'active' },
  { id: 'c3-g-15', admissionNo: 'AD-3015', name: 'FATHIMA HADIYA M', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-A', rollNo: 15, isLeader: false, chestNo: 266, status: 'active' },
  { id: 'c3-g-18', admissionNo: 'AD-3018', name: 'FATHIMA ZAKIYYA NK', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-B', rollNo: 18, isLeader: false, chestNo: 166, status: 'active' },
  { id: 'c3-g-19', admissionNo: 'AD-3019', name: 'RAIHA KADHEEJA V', classNum: 'Class 3', category: 'Sub Junior', gender: 'Girls', group: 'GRP-C', rollNo: 19, isLeader: false, chestNo: 366, status: 'active' },

  // CLASS 4 BOYS (10 Students)
  { id: 'c4-b-3', admissionNo: 'AD-4003', name: 'MUHAMMED RAYYAN. U', classNum: 'Class 4', category: 'Sub Junior', gender: 'Boys', group: 'GRP-C', rollNo: 3, isLeader: false, chestNo: 316, status: 'active' },
  { id: 'c4-b-4', admissionNo: 'AD-4004', name: 'SHADIL SHAN. V', classNum: 'Class 4', category: 'Sub Junior', gender: 'Boys', group: 'GRP-A', rollNo: 4, isLeader: false, chestNo: 217, status: 'active' },
  { id: 'c4-b-5', admissionNo: 'AD-4005', name: 'MUHAMMED MUHSIN. K', classNum: 'Class 4', category: 'Sub Junior', gender: 'Boys', group: 'GRP-B', rollNo: 5, isLeader: false, chestNo: 117, status: 'active' },
  { id: 'c4-b-6', admissionNo: 'AD-4006', name: 'ABISH MUHAMMED. K. P', classNum: 'Class 4', category: 'Sub Junior', gender: 'Boys', group: 'GRP-C', rollNo: 6, isLeader: false, chestNo: 317, status: 'active' },
  { id: 'c4-b-7', admissionNo: 'AD-4007', name: 'MUHAMMED FARHAN.C', classNum: 'Class 4', category: 'Sub Junior', gender: 'Boys', group: 'GRP-A', rollNo: 7, isLeader: false, chestNo: 218, status: 'active' },
  { id: 'c4-b-8', admissionNo: 'AD-4008', name: 'MUHAMMED ANAS.K', classNum: 'Class 4', category: 'Sub Junior', gender: 'Boys', group: 'GRP-B', rollNo: 8, isLeader: false, chestNo: 118, status: 'active' },
  { id: 'c4-b-9', admissionNo: 'AD-4009', name: 'MUHAMMED NAJIL.P', classNum: 'Class 4', category: 'Sub Junior', gender: 'Boys', group: 'GRP-C', rollNo: 9, isLeader: false, chestNo: 318, status: 'active' },
  { id: 'c4-b-10', admissionNo: 'AD-4010', name: 'MUHAMMED ASHAD.P', classNum: 'Class 4', category: 'Sub Junior', gender: 'Boys', group: 'GRP-A', rollNo: 10, isLeader: false, chestNo: 219, status: 'active' },
  { id: 'c4-b-18', admissionNo: 'AD-4018', name: 'MUHAMMED SHIZAN. M', classNum: 'Class 4', category: 'Sub Junior', gender: 'Boys', group: 'GRP-B', rollNo: 18, isLeader: false, chestNo: 119, status: 'active' },
  { id: 'c4-b-20', admissionNo: 'AD-4020', name: 'MUHAMMED BISHR. K', classNum: 'Class 4', category: 'Sub Junior', gender: 'Boys', group: 'GRP-C', rollNo: 20, isLeader: false, chestNo: 319, status: 'active' },

  // CLASS 4 GIRLS (11 Students)
  { id: 'c4-g-1', admissionNo: 'AD-4001', name: 'FATHIMA DIYA M', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-A', rollNo: 1, isLeader: false, chestNo: 267, status: 'active' },
  { id: 'c4-g-2', admissionNo: 'AD-4002', name: 'FATHIMA FAHINSHA M', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-B', rollNo: 2, isLeader: false, chestNo: 167, status: 'active' },
  { id: 'c4-g-11', admissionNo: 'AD-4011', name: 'FARVA FATHIMA. V', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-C', rollNo: 11, isLeader: false, chestNo: 367, status: 'active' },
  { id: 'c4-g-12', admissionNo: 'AD-4012', name: 'YUMNA FATHIMA. K', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-A', rollNo: 12, isLeader: false, chestNo: 268, status: 'active' },
  { id: 'c4-g-13', admissionNo: 'AD-4013', name: 'REEHA FATHIMA. M', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-B', rollNo: 13, isLeader: false, chestNo: 168, status: 'active' },
  { id: 'c4-g-14', admissionNo: 'AD-4014', name: 'AYISHA FILZA. K', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-C', rollNo: 14, isLeader: false, chestNo: 368, status: 'active' },
  { id: 'c4-g-15', admissionNo: 'AD-4015', name: 'FATHIMA HANA. K', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-A', rollNo: 15, isLeader: false, chestNo: 269, status: 'active' },
  { id: 'c4-g-16', admissionNo: 'AD-4016', name: 'SHAZA FATHIMA. M', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-B', rollNo: 16, isLeader: false, chestNo: 169, status: 'active' },
  { id: 'c4-g-17', admissionNo: 'AD-4017', name: 'AYISHA RIZA. K', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-C', rollNo: 17, isLeader: false, chestNo: 369, status: 'active' },
  { id: 'c4-g-19', admissionNo: 'AD-4019', name: 'SHAZA MAHARIN. M', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-A', rollNo: 19, isLeader: false, chestNo: 270, status: 'active' },
  { id: 'c4-g-21', admissionNo: 'AD-4021', name: 'IZZA FATHIMA V', classNum: 'Class 4', category: 'Sub Junior', gender: 'Girls', group: 'GRP-B', rollNo: 21, isLeader: false, chestNo: 170, status: 'active' },

  // CLASS 5 BOYS (13 Students)
  { id: 'c5-b-1', admissionNo: 'AD-5001', name: 'FESIN AHMED MK', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 1, isLeader: false, chestNo: 220, status: 'active' },
  { id: 'c5-b-2', admissionNo: 'AD-5002', name: 'MUHAMMED MUZAMMIL K', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 2, isLeader: false, chestNo: 120, status: 'active' },
  { id: 'c5-b-3', admissionNo: 'AD-5003', name: 'MUHAMMED AFLAH M', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 3, isLeader: false, chestNo: 320, status: 'active' },
  { id: 'c5-b-4', admissionNo: 'AD-5004', name: 'MUHAMMED FASI VK', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 4, isLeader: false, chestNo: 221, status: 'active' },
  { id: 'c5-b-5', admissionNo: 'AD-5005', name: 'MUHAMMED ADHIL K', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 5, isLeader: false, chestNo: 121, status: 'active' },
  { id: 'c5-b-10', admissionNo: 'AD-5010', name: 'MUHAMMED FADHI M', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 10, isLeader: false, chestNo: 321, status: 'active' },
  { id: 'c5-b-11', admissionNo: 'AD-5011', name: 'MUHAMMED SHABIL NK', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 11, isLeader: false, chestNo: 222, status: 'active' },
  { id: 'c5-b-12', admissionNo: 'AD-5012', name: 'MUHAMMED SHADIN V', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 12, isLeader: false, chestNo: 122, status: 'active' },
  { id: 'c5-b-13', admissionNo: 'AD-5013', name: 'MUHAMMED SAYAN K', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 13, isLeader: false, chestNo: 322, status: 'active' },
  { id: 'c5-b-14', admissionNo: 'AD-5014', name: 'AJFAN AHMED K', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 14, isLeader: false, chestNo: 223, status: 'active' },
  { id: 'c5-b-15', admissionNo: 'AD-5015', name: 'ABDU RAHEEM K', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 15, isLeader: false, chestNo: 123, status: 'active' },
  { id: 'c5-b-16', admissionNo: 'AD-5016', name: 'MUHAMMED SHAN V', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 16, isLeader: false, chestNo: 323, status: 'active' },
  { id: 'c5-b-17', admissionNo: 'AD-5017', name: 'MUHAMMED SIDQ MP', classNum: 'Class 5', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 17, isLeader: false, chestNo: 224, status: 'active' },

  // CLASS 5 GIRLS (14 Students)
  { id: 'c5-g-6', admissionNo: 'AD-5006', name: 'FATHIMA SAFWA M', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 6, isLeader: false, chestNo: 370, status: 'active' },
  { id: 'c5-g-7', admissionNo: 'AD-5007', name: 'NASLA FATHIMA MK', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 7, isLeader: false, chestNo: 271, status: 'active' },
  { id: 'c5-g-8', admissionNo: 'AD-5008', name: 'HIZA FATHIMA KP', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 8, isLeader: false, chestNo: 171, status: 'active' },
  { id: 'c5-g-9', admissionNo: 'AD-5009', name: 'FATHIMA SHASA VK', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 9, isLeader: false, chestNo: 371, status: 'active' },
  { id: 'c5-g-18', admissionNo: 'AD-5018', name: 'ISHA MEHARIN V', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 18, isLeader: false, chestNo: 272, status: 'active' },
  { id: 'c5-g-19', admissionNo: 'AD-5019', name: 'JAZA FATHIMA VK', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 19, isLeader: false, chestNo: 172, status: 'active' },
  { id: 'c5-g-20', admissionNo: 'AD-5020', name: 'NIYA FATHIMA K', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 20, isLeader: false, chestNo: 372, status: 'active' },
  { id: 'c5-g-21', admissionNo: 'AD-5021', name: 'FATHIMA NAZMI K', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 21, isLeader: false, chestNo: 273, status: 'active' },
  { id: 'c5-g-22', admissionNo: 'AD-5022', name: 'FATHIMA RIYA M', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 22, isLeader: false, chestNo: 173, status: 'active' },
  { id: 'c5-g-23', admissionNo: 'AD-5023', name: 'ISHA MEHARIN NK', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 23, isLeader: false, chestNo: 373, status: 'active' },
  { id: 'c5-g-24', admissionNo: 'AD-5024', name: 'NAINA MEHARIN KP', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 24, isLeader: false, chestNo: 274, status: 'active' },
  { id: 'c5-g-25', admissionNo: 'AD-5025', name: 'ISMATH NAHAAN KP', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 25, isLeader: false, chestNo: 174, status: 'active' },
  { id: 'c5-g-26', admissionNo: 'AD-5026', name: 'ANIYA FATHIMA M', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 26, isLeader: false, chestNo: 374, status: 'active' },
  { id: 'c5-g-27', admissionNo: 'AD-5027', name: 'NADSHA FATHIMA V', classNum: 'Class 5', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 27, isLeader: false, chestNo: 275, status: 'active' },

  // CLASS 6 BOYS (16 Students)
  { id: 'c6-b-1', admissionNo: 'AD-6001', name: 'MUHAMMED RASHDAN MP', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 1, isLeader: false, chestNo: 124, status: 'active' },
  { id: 'c6-b-2', admissionNo: 'AD-6002', name: 'MUHAMMED ADIL M', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 2, isLeader: false, chestNo: 324, status: 'active' },
  { id: 'c6-b-3', admissionNo: 'AD-6003', name: 'MUHAMMED FARHAN K', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 3, isLeader: false, chestNo: 225, status: 'active' },
  { id: 'c6-b-4', admissionNo: 'AD-6004', name: 'MUHAMMED RIFIN N', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 4, isLeader: false, chestNo: 125, status: 'active' },
  { id: 'c6-b-9', admissionNo: 'AD-6009', name: 'MUHAMMED DANISH VK', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 9, isLeader: false, chestNo: 325, status: 'active' },
  { id: 'c6-b-10', admissionNo: 'AD-6010', name: 'MUHAMMED JISHMIL V', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 10, isLeader: false, chestNo: 226, status: 'active' },
  { id: 'c6-b-11', admissionNo: 'AD-6011', name: 'MUHAMMED SHIHAM KP', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 11, isLeader: false, chestNo: 126, status: 'active' },
  { id: 'c6-b-12', admissionNo: 'AD-6012', name: 'MUHAMMED NISHAL KP', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 12, isLeader: false, chestNo: 326, status: 'active' },
  { id: 'c6-b-13', admissionNo: 'AD-6013', name: 'MUHAMMED SAHAD K', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 13, isLeader: false, chestNo: 227, status: 'active' },
  { id: 'c6-b-14', admissionNo: 'AD-6014', name: 'MUHAMMED ADHIL K', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 14, isLeader: false, chestNo: 127, status: 'active' },
  { id: 'c6-b-15', admissionNo: 'AD-6015', name: 'ABDUL MUHAIMIN KP', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 15, isLeader: false, chestNo: 327, status: 'active' },
  { id: 'c6-b-16', admissionNo: 'AD-6016', name: 'MUHAMMED HASHIM M', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 16, isLeader: false, chestNo: 228, status: 'active' },
  { id: 'c6-b-17', admissionNo: 'AD-6017', name: 'MUHAMMED SHAMEEL K', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 17, isLeader: false, chestNo: 128, status: 'active' },
  { id: 'c6-b-18', admissionNo: 'AD-6018', name: 'AHAMMED SHAHM K', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 18, isLeader: false, chestNo: 328, status: 'active' },
  { id: 'c6-b-19', admissionNo: 'AD-6019', name: 'MUHAMMED RIYAN V', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 19, isLeader: false, chestNo: 229, status: 'active' },
  { id: 'c6-b-35', admissionNo: 'AD-6035', name: 'MUHAMMED SHIFAN. M', classNum: 'Class 6', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 35, isLeader: false, chestNo: 129, status: 'active' },

  // CLASS 6 GIRLS (19 Students)
  { id: 'c6-g-5', admissionNo: 'AD-6005', name: 'SHARBINA M', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 5, isLeader: false, chestNo: 175, status: 'active' },
  { id: 'c6-g-6', admissionNo: 'AD-6006', name: 'FATHIMA ZUHRA N K', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 6, isLeader: false, chestNo: 375, status: 'active' },
  { id: 'c6-g-7', admissionNo: 'AD-6007', name: 'SAJVA FATHIMA V', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 7, isLeader: false, chestNo: 276, status: 'active' },
  { id: 'c6-g-8', admissionNo: 'AD-6008', name: 'FATHIMA HIBA M K', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 8, isLeader: false, chestNo: 176, status: 'active' },
  { id: 'c6-g-20', admissionNo: 'AD-6020', name: 'DIYA FATHIMA K', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 20, isLeader: false, chestNo: 376, status: 'active' },
  { id: 'c6-g-21', admissionNo: 'AD-6021', name: 'FATHIMA LIBA K', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 21, isLeader: false, chestNo: 277, status: 'active' },
  { id: 'c6-g-22', admissionNo: 'AD-6022', name: 'FATHIMA SHIFA M', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 22, isLeader: false, chestNo: 177, status: 'active' },
  { id: 'c6-g-23', admissionNo: 'AD-6023', name: 'FATHIMA SAFA P', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 23, isLeader: false, chestNo: 377, status: 'active' },
  { id: 'c6-g-24', admissionNo: 'AD-6024', name: 'FATHIMA HANEEN P', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 24, isLeader: false, chestNo: 278, status: 'active' },
  { id: 'c6-g-25', admissionNo: 'AD-6025', name: 'VAHEEJA K', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 25, isLeader: false, chestNo: 178, status: 'active' },
  { id: 'c6-g-26', admissionNo: 'AD-6026', name: 'FATHIMA SHIRIN M', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 26, isLeader: false, chestNo: 378, status: 'active' },
  { id: 'c6-g-27', admissionNo: 'AD-6027', name: 'FATHIMA HANAN KP', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 27, isLeader: false, chestNo: 279, status: 'active' },
  { id: 'c6-g-28', admissionNo: 'AD-6028', name: 'HIBA FATHIMA KP', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 28, isLeader: false, chestNo: 179, status: 'active' },
  { id: 'c6-g-29', admissionNo: 'AD-6029', name: 'RANIYA KP', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 29, isLeader: false, chestNo: 379, status: 'active' },
  { id: 'c6-g-30', admissionNo: 'AD-6030', name: 'DIYA FATHIMA M', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 30, isLeader: false, chestNo: 280, status: 'active' },
  { id: 'c6-g-31', admissionNo: 'AD-6031', name: 'FATHIMA FAIHA C', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 31, isLeader: false, chestNo: 180, status: 'active' },
  { id: 'c6-g-32', admissionNo: 'AD-6032', name: 'FATHIMA NK', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 32, isLeader: false, chestNo: 380, status: 'active' },
  { id: 'c6-g-33', admissionNo: 'AD-6033', name: 'SHASMIN SAHAR KP', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 33, isLeader: false, chestNo: 281, status: 'active' },
  { id: 'c6-g-34', admissionNo: 'AD-6034', name: 'FATHIMA ADHEELA K', classNum: 'Class 6', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 34, isLeader: false, chestNo: 181, status: 'active' },

  // CLASS 7 BOYS (10 Students)
  { id: 'c7-b-1', admissionNo: 'AD-7001', name: 'MUHAMMED SHADIL V', classNum: 'Class 7', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 1, isLeader: false, chestNo: 329, status: 'active' },
  { id: 'c7-b-2', admissionNo: 'AD-7002', name: 'MUHAMMED JISHAN V', classNum: 'Class 7', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 2, isLeader: false, chestNo: 230, status: 'active' },
  { id: 'c7-b-3', admissionNo: 'AD-7003', name: 'MUHAMMED ASAL V', classNum: 'Class 7', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 3, isLeader: false, chestNo: 130, status: 'active' },
  { id: 'c7-b-4', admissionNo: 'AD-7004', name: 'MUHAMMED AJFAL.C', classNum: 'Class 7', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 4, isLeader: false, chestNo: 330, status: 'active' },
  { id: 'c7-b-11', admissionNo: 'AD-7011', name: 'MUHAMMED MIDLAJ K', classNum: 'Class 7', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 11, isLeader: false, chestNo: 231, status: 'active' },
  { id: 'c7-b-12', admissionNo: 'AD-7012', name: 'MUHAMMED MUSTHAFA K', classNum: 'Class 7', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 12, isLeader: false, chestNo: 131, status: 'active' },
  { id: 'c7-b-14', admissionNo: 'AD-7014', name: 'MUHAMMED SHIBLI. V', classNum: 'Class 7', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 14, isLeader: false, chestNo: 331, status: 'active' },
  { id: 'c7-b-18', admissionNo: 'AD-7018', name: 'MUHAMMED AMEEN. K. P', classNum: 'Class 7', category: 'Junior', gender: 'Boys', group: 'GRP-A', rollNo: 18, isLeader: false, chestNo: 232, status: 'active' },
  { id: 'c7-b-19', admissionNo: 'AD-7019', name: 'MUHAMMED RIFIN. K', classNum: 'Class 7', category: 'Junior', gender: 'Boys', group: 'GRP-B', rollNo: 19, isLeader: false, chestNo: 132, status: 'active' },
  { id: 'c7-b-20', admissionNo: 'AD-7020', name: 'MUHAMMED SHANIL K', classNum: 'Class 7', category: 'Junior', gender: 'Boys', group: 'GRP-C', rollNo: 20, isLeader: false, chestNo: 332, status: 'active' },

  // CLASS 7 GIRLS (10 Students)
  { id: 'c7-g-5', admissionNo: 'AD-7005', name: 'NIYA MINHA K P', classNum: 'Class 7', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 5, isLeader: false, chestNo: 381, status: 'active' },
  { id: 'c7-g-6', admissionNo: 'AD-7006', name: 'HUSNA M', classNum: 'Class 7', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 6, isLeader: false, chestNo: 282, status: 'active' },
  { id: 'c7-g-7', admissionNo: 'AD-7007', name: 'NAJVA FATHIMA K', classNum: 'Class 7', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 7, isLeader: false, chestNo: 182, status: 'active' },
  { id: 'c7-g-8', admissionNo: 'AD-7008', name: 'FATHIMA HANIYYA M', classNum: 'Class 7', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 8, isLeader: false, chestNo: 382, status: 'active' },
  { id: 'c7-g-9', admissionNo: 'AD-7009', name: 'AMNA M', classNum: 'Class 7', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 9, isLeader: false, chestNo: 283, status: 'active' },
  { id: 'c7-g-10', admissionNo: 'AD-7010', name: 'FATHIMA MINSHA V', classNum: 'Class 7', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 10, isLeader: false, chestNo: 183, status: 'active' },
  { id: 'c7-g-13', admissionNo: 'AD-7013', name: 'DILNA SHARIN M', classNum: 'Class 7', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 13, isLeader: false, chestNo: 383, status: 'active' },
  { id: 'c7-g-15', admissionNo: 'AD-7015', name: 'NISHANA BANU. V', classNum: 'Class 7', category: 'Junior', gender: 'Girls', group: 'GRP-A', rollNo: 15, isLeader: false, chestNo: 284, status: 'active' },
  { id: 'c7-g-16', admissionNo: 'AD-7016', name: 'SWALIHA. K', classNum: 'Class 7', category: 'Junior', gender: 'Girls', group: 'GRP-B', rollNo: 16, isLeader: false, chestNo: 184, status: 'active' },
  { id: 'c7-g-17', admissionNo: 'AD-7017', name: 'FATHIMA NAJA. K. P', classNum: 'Class 7', category: 'Junior', gender: 'Girls', group: 'GRP-C', rollNo: 17, isLeader: false, chestNo: 384, status: 'active' },

  // CLASS 8 BOYS (8 Students)
  { id: 'c8-b-1', admissionNo: 'AD-8001', name: 'MUHAMMED MINHAL K', classNum: 'Class 8', category: 'Senior', gender: 'Boys', group: 'GRP-A', rollNo: 1, isLeader: true, leaderRank: '3rd Leader', chestNo: 203, status: 'active' },
  { id: 'c8-b-2', admissionNo: 'AD-8002', name: 'MUHAMMED ANAS V', classNum: 'Class 8', category: 'Senior', gender: 'Boys', group: 'GRP-B', rollNo: 2, isLeader: true, leaderRank: '3rd Leader', chestNo: 103, status: 'active' },
  { id: 'c8-b-3', admissionNo: 'AD-8003', name: 'RAIHAN PK', classNum: 'Class 8', category: 'Senior', gender: 'Boys', group: 'GRP-C', rollNo: 3, isLeader: true, leaderRank: '3rd Leader', chestNo: 303, status: 'active' },
  { id: 'c8-b-4', admissionNo: 'AD-8004', name: 'MUHAMMED JISHAN VK', classNum: 'Class 8', category: 'Senior', gender: 'Boys', group: 'GRP-A', rollNo: 4, isLeader: false, chestNo: 234, status: 'active' },
  { id: 'c8-b-5', admissionNo: 'AD-8005', name: 'MUHAMMED FAINAN C', classNum: 'Class 8', category: 'Senior', gender: 'Boys', group: 'GRP-B', rollNo: 5, isLeader: false, chestNo: 134, status: 'active' },
  { id: 'c8-b-6', admissionNo: 'AD-8006', name: 'MUHAMMED DILSHAD V', classNum: 'Class 8', category: 'Senior', gender: 'Boys', group: 'GRP-C', rollNo: 6, isLeader: false, chestNo: 334, status: 'active' },
  { id: 'c8-b-7', admissionNo: 'AD-8007', name: 'MUHAMMED RAIHAN M', classNum: 'Class 8', category: 'Senior', gender: 'Boys', group: 'GRP-A', rollNo: 7, isLeader: false, chestNo: 235, status: 'active' },
  { id: 'c8-b-8', admissionNo: 'AD-8008', name: 'RAYAN PK', classNum: 'Class 8', category: 'Senior', gender: 'Boys', group: 'GRP-B', rollNo: 8, isLeader: false, chestNo: 135, status: 'active' },

  // CLASS 8 GIRLS (8 Students)
  { id: 'c8-g-1', admissionNo: 'AD-8001-G', name: 'AMNA FATHIMA K', classNum: 'Class 8', category: 'Senior', gender: 'Girls', group: 'GRP-A', rollNo: 1, isLeader: true, leaderRank: '3rd Leader', chestNo: 252, status: 'active' },
  { id: 'c8-g-2', admissionNo: 'AD-8002-G', name: 'IZZA FATHIMA M', classNum: 'Class 8', category: 'Senior', gender: 'Girls', group: 'GRP-B', rollNo: 2, isLeader: true, leaderRank: '3rd Leader', chestNo: 152, status: 'active' },
  { id: 'c8-g-3', admissionNo: 'AD-8003-G', name: 'FATHIMA SAFA K', classNum: 'Class 8', category: 'Senior', gender: 'Girls', group: 'GRP-C', rollNo: 3, isLeader: true, leaderRank: '3rd Leader', chestNo: 352, status: 'active' },
  { id: 'c8-g-4', admissionNo: 'AD-8004-G', name: 'NASLA FATHIMA K', classNum: 'Class 8', category: 'Senior', gender: 'Girls', group: 'GRP-A', rollNo: 4, isLeader: false, chestNo: 286, status: 'active' },
  { id: 'c8-g-5', admissionNo: 'AD-8005-G', name: 'FATHIMA JINSIYA K', classNum: 'Class 8', category: 'Senior', gender: 'Girls', group: 'GRP-B', rollNo: 5, isLeader: false, chestNo: 186, status: 'active' },
  { id: 'c8-g-6', admissionNo: 'AD-8006-G', name: 'RIDHA FATHIMA KP', classNum: 'Class 8', category: 'Senior', gender: 'Girls', group: 'GRP-C', rollNo: 6, isLeader: false, chestNo: 386, status: 'active' },
  { id: 'c8-g-7', admissionNo: 'AD-8007-G', name: 'BINSHIDA M', classNum: 'Class 8', category: 'Senior', gender: 'Girls', group: 'GRP-A', rollNo: 7, isLeader: false, chestNo: 287, status: 'active' },
  { id: 'c8-g-8', admissionNo: 'AD-8008-G', name: 'FATHIMA HADIYA K', classNum: 'Class 8', category: 'Senior', gender: 'Girls', group: 'GRP-B', rollNo: 8, isLeader: false, chestNo: 187, status: 'active' },

  // CLASS 9 BOYS (11 Students)
  { id: 'c9-b-1', admissionNo: 'AD-9001', name: 'MUHAMMED JASEEM K', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-A', rollNo: 1, isLeader: true, leaderRank: '2nd Leader', chestNo: 202, status: 'active' },
  { id: 'c9-b-2', admissionNo: 'AD-9002', name: 'MUHAMMED SHAYAN MK', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-B', rollNo: 2, isLeader: true, leaderRank: '2nd Leader', chestNo: 102, status: 'active' },
  { id: 'c9-b-3', admissionNo: 'AD-9003', name: 'MIJVAD K', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-C', rollNo: 3, isLeader: true, leaderRank: '2nd Leader', chestNo: 302, status: 'active' },
  { id: 'c9-b-4', admissionNo: 'AD-9004', name: 'YASEEN MUBARAK K', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-C', rollNo: 4, isLeader: false, chestNo: 336, status: 'active' },
  { id: 'c9-b-5', admissionNo: 'AD-9005', name: 'MUHAMMED JINSHID V', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-A', rollNo: 5, isLeader: false, chestNo: 237, status: 'active' },
  { id: 'c9-b-6', admissionNo: 'AD-9006', name: 'AMEER ADAM V', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-B', rollNo: 6, isLeader: false, chestNo: 137, status: 'active' },
  { id: 'c9-b-7', admissionNo: 'AD-9007', name: 'ASHMIL MUHAMMED K', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-C', rollNo: 7, isLeader: false, chestNo: 337, status: 'active' },
  { id: 'c9-b-8', admissionNo: 'AD-9008', name: 'MUHAMMED SHIFIN NK', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-A', rollNo: 8, isLeader: false, chestNo: 238, status: 'active' },
  { id: 'c9-b-9', admissionNo: 'AD-9009', name: 'MUHAMMED SHAFEEI M', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-B', rollNo: 9, isLeader: false, chestNo: 138, status: 'active' },
  { id: 'c9-b-10', admissionNo: 'AD-9010', name: 'MUHAMMED SAVAD M', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-C', rollNo: 10, isLeader: false, chestNo: 338, status: 'active' },
  { id: 'c9-b-11', admissionNo: 'AD-9011', name: 'MUHAMMED SHANIL KP', classNum: 'Class 9', category: 'Senior', gender: 'Boys', group: 'GRP-A', rollNo: 11, isLeader: false, chestNo: 239, status: 'active' },

  // CLASS 9 GIRLS (11 Students)
  { id: 'c9-g-1', admissionNo: 'AD-9001-G', name: 'FARHA V', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-A', rollNo: 1, isLeader: true, leaderRank: '2nd Leader', chestNo: 251, status: 'active' },
  { id: 'c9-g-2', admissionNo: 'AD-9002-G', name: 'AYISHA AJWA K', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-B', rollNo: 2, isLeader: true, leaderRank: '2nd Leader', chestNo: 151, status: 'active' },
  { id: 'c9-g-3', admissionNo: 'AD-9003-G', name: 'FATHIMA LAIBA KP', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-C', rollNo: 3, isLeader: true, leaderRank: '2nd Leader', chestNo: 351, status: 'active' },
  { id: 'c9-g-4', admissionNo: 'AD-9004-G', name: 'FATHIMA HADIYA M', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-C', rollNo: 4, isLeader: false, chestNo: 388, status: 'active' },
  { id: 'c9-g-5', admissionNo: 'AD-9005-G', name: 'FATHIMA RUSHDHA K', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-A', rollNo: 5, isLeader: false, chestNo: 289, status: 'active' },
  { id: 'c9-g-6', admissionNo: 'AD-9006-G', name: 'FATHIMA SHIFA KP', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-B', rollNo: 6, isLeader: false, chestNo: 189, status: 'active' },
  { id: 'c9-g-7', admissionNo: 'AD-9007-G', name: 'INSHA FATHIMA VK', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-C', rollNo: 7, isLeader: false, chestNo: 389, status: 'active' },
  { id: 'c9-g-8', admissionNo: 'AD-9008-G', name: 'NAJA THASNEEM P', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-A', rollNo: 8, isLeader: false, chestNo: 290, status: 'active' },
  { id: 'c9-g-9', admissionNo: 'AD-9009-G', name: 'SAFA KP', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-B', rollNo: 9, isLeader: false, chestNo: 190, status: 'active' },
  { id: 'c9-g-10', admissionNo: 'AD-9010-G', name: 'FATHIMA SANA P', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-C', rollNo: 10, isLeader: false, chestNo: 390, status: 'active' },
  { id: 'c9-g-11', admissionNo: 'AD-9011-G', name: 'SAFA MOL', classNum: 'Class 9', category: 'Senior', gender: 'Girls', group: 'GRP-A', rollNo: 11, isLeader: false, chestNo: 291, status: 'active' },

  // CLASS 10 BOYS (9 Students)
  { id: 'c10-b-1', admissionNo: 'AD-10001', name: 'MUHAMMED AMEEN M', classNum: 'Class 10', category: 'Senior', gender: 'Boys', group: 'GRP-A', rollNo: 1, isLeader: true, leaderRank: '1st Leader', chestNo: 201, status: 'active' },
  { id: 'c10-b-2', admissionNo: 'AD-10002', name: 'MUHAMMED RASHAD NK', classNum: 'Class 10', category: 'Senior', gender: 'Boys', group: 'GRP-B', rollNo: 2, isLeader: true, leaderRank: '1st Leader', chestNo: 101, status: 'active' },
  { id: 'c10-b-3', admissionNo: 'AD-10003', name: 'MUHAMMED SAHAL M', classNum: 'Class 10', category: 'Senior', gender: 'Boys', group: 'GRP-C', rollNo: 3, isLeader: true, leaderRank: '1st Leader', chestNo: 301, status: 'active' },
  { id: 'c10-b-4', admissionNo: 'AD-10004', name: 'MUHAMMED MINHAJ K', classNum: 'Class 10', category: 'Senior', gender: 'Boys', group: 'GRP-B', rollNo: 4, isLeader: false, chestNo: 140, status: 'active' },
  { id: 'c10-b-5', admissionNo: 'AD-10005', name: 'MUHAMMED ISHAN V', classNum: 'Class 10', category: 'Senior', gender: 'Boys', group: 'GRP-C', rollNo: 5, isLeader: false, chestNo: 340, status: 'active' },
  { id: 'c10-b-6', admissionNo: 'AD-10006', name: 'MUHAMMED SHAMMAS M', classNum: 'Class 10', category: 'Senior', gender: 'Boys', group: 'GRP-A', rollNo: 6, isLeader: false, chestNo: 241, status: 'active' },
  { id: 'c10-b-7', admissionNo: 'AD-10007', name: 'MUHAMMED AMAN V', classNum: 'Class 10', category: 'Senior', gender: 'Boys', group: 'GRP-B', rollNo: 7, isLeader: false, chestNo: 141, status: 'active' },
  { id: 'c10-b-8', admissionNo: 'AD-10008', name: 'MUHAMMED LUBAIB M', classNum: 'Class 10', category: 'Senior', gender: 'Boys', group: 'GRP-C', rollNo: 8, isLeader: false, chestNo: 341, status: 'active' },
  { id: 'c10-b-9', admissionNo: 'AD-10009', name: 'MUHAMMED ANSHIF', classNum: 'Class 10', category: 'Senior', gender: 'Boys', group: 'GRP-A', rollNo: 9, isLeader: false, chestNo: 242, status: 'active' },

  // CLASS 10 GIRLS (10 Students)
  { id: 'c10-g-1', admissionNo: 'AD-10001-G', name: 'RISHNA FATHIMA', classNum: 'Class 10', category: 'Senior', gender: 'Girls', group: 'GRP-A', rollNo: 1, isLeader: true, leaderRank: '1st Leader', chestNo: 250, status: 'active' },
  { id: 'c10-g-2', admissionNo: 'AD-10002-G', name: 'FATHIMA HUDHA', classNum: 'Class 10', category: 'Senior', gender: 'Girls', group: 'GRP-B', rollNo: 2, isLeader: true, leaderRank: '1st Leader', chestNo: 150, status: 'active' },
  { id: 'c10-g-3', admissionNo: 'AD-10003-G', name: 'MINHA SHERIN', classNum: 'Class 10', category: 'Senior', gender: 'Girls', group: 'GRP-C', rollNo: 3, isLeader: true, leaderRank: '1st Leader', chestNo: 350, status: 'active' },
  { id: 'c10-g-4', admissionNo: 'AD-10004-G', name: 'FATHIMA FAMNA', classNum: 'Class 10', category: 'Senior', gender: 'Girls', group: 'GRP-B', rollNo: 4, isLeader: false, chestNo: 192, status: 'active' },
  { id: 'c10-g-5', admissionNo: 'AD-10005-G', name: 'FATHIMA FAIROOSA', classNum: 'Class 10', category: 'Senior', gender: 'Girls', group: 'GRP-C', rollNo: 5, isLeader: false, chestNo: 392, status: 'active' },
  { id: 'c10-g-6', admissionNo: 'AD-10006-G', name: 'FATHIMA HIBA', classNum: 'Class 10', category: 'Senior', gender: 'Girls', group: 'GRP-A', rollNo: 6, isLeader: false, chestNo: 293, status: 'active' },
  { id: 'c10-g-7', admissionNo: 'AD-10007-G', name: 'FATHIMA HENNA', classNum: 'Class 10', category: 'Senior', gender: 'Girls', group: 'GRP-B', rollNo: 7, isLeader: false, chestNo: 193, status: 'active' },
  { id: 'c10-g-8', admissionNo: 'AD-10008-G', name: 'SANA BILSHA', classNum: 'Class 10', category: 'Senior', gender: 'Girls', group: 'GRP-C', rollNo: 8, isLeader: false, chestNo: 393, status: 'active' },
  { id: 'c10-g-9', admissionNo: 'AD-10009-G', name: 'FATHIMA LIYANA', classNum: 'Class 10', category: 'Senior', gender: 'Girls', group: 'GRP-A', rollNo: 9, isLeader: false, chestNo: 294, status: 'active' },
  { id: 'c10-g-10', admissionNo: 'AD-10010-G', name: 'FATHIMA HASEEFA', classNum: 'Class 10', category: 'Senior', gender: 'Girls', group: 'GRP-B', rollNo: 10, isLeader: false, chestNo: 194, status: 'active' },
];

export const INITIAL_EVENTS = [
  {
    id: 'evt-1',
    title: 'ഗദ്യ വായന (അറബിമലയാളം)',
    category: 'Sub Junior',
    gender: 'Boys',
    type: 'Non-Stage',
    time: '01:30 PM',
    location: 'Hall A',
    date: '2026-08-09',
    status: 'Upcoming',
  },
  {
    id: 'evt-2',
    title: 'ഗദ്യ വായന (അറബിമലയാളം)',
    category: 'Sub Junior',
    gender: 'Girls',
    type: 'Non-Stage',
    time: '01:30 PM',
    location: 'Hall B',
    date: '2026-08-09',
    status: 'Upcoming',
  },
  {
    id: 'evt-3',
    title: 'വാർത്താ വായന',
    category: 'Senior',
    gender: 'Boys',
    type: 'Non-Stage',
    time: '01:30 PM',
    location: 'Hall A',
    date: '2026-08-09',
    status: 'Upcoming',
  },
  {
    id: 'evt-4',
    title: 'വാർത്താ വായന',
    category: 'Senior',
    gender: 'Girls',
    type: 'Non-Stage',
    time: '01:30 PM',
    location: 'Hall B',
    date: '2026-08-09',
    status: 'Upcoming',
  },
  {
    id: 'evt-5',
    title: 'കളറിംഗ്',
    category: 'Kiddies',
    gender: 'Boys',
    type: 'Non-Stage',
    time: '02:00 PM',
    location: 'Hall A',
    date: '2026-08-09',
    status: 'Upcoming',
  },
  {
    id: 'evt-6',
    title: 'കിസാ പാട്ട്',
    category: 'Junior',
    gender: 'Boys',
    type: 'Stage',
    time: '03:00 PM',
    location: 'Main Stage',
    date: '2026-08-09',
    status: 'Live',
  },
  {
    id: 'evt-7',
    title: 'ഖുർആൻ പാരായണം',
    category: 'Junior',
    gender: 'Girls',
    type: 'Non-Stage',
    time: '03:30 PM',
    location: 'Hall B',
    date: '2026-08-09',
    status: 'Completed',
  },
  {
    id: 'evt-8',
    title: 'പ്രസംഗം (മലയാളം)',
    category: 'Senior',
    gender: 'Boys',
    type: 'Stage',
    time: '04:00 PM',
    location: 'Main Stage',
    date: '2026-08-09',
    status: 'Completed',
  },
  {
    id: 'evt-9',
    title: 'ഗാനം (അറബിക്)',
    category: 'General',
    gender: 'Boys',
    type: 'Stage',
    time: '05:00 PM',
    location: 'Main Stage',
    date: '2026-08-09',
    status: 'Completed',
  },
];

export const INITIAL_RESULTS = {
  'evt-7': {
    eventId: 'evt-7',
    publishedAt: '2026-08-09T15:45:00Z',
    first: { studentId: 'c6-g-21', chestNo: 277, name: 'FATHIMA LIBA K', group: 'GRP-A', points: 10 },
    second: { studentId: 'c6-g-20', chestNo: 376, name: 'DIYA FATHIMA K', group: 'GRP-C', points: 7 },
    third: { studentId: 'c7-g-16', chestNo: 184, name: 'SWALIHA. K', group: 'GRP-B', points: 5 },
  },
  'evt-8': {
    eventId: 'evt-8',
    publishedAt: '2026-08-09T16:30:00Z',
    first: { studentId: 'c10-b-4', chestNo: 140, name: 'MUHAMMED MINHAJ K', group: 'GRP-B', points: 10 },
    second: { studentId: 'c9-b-7', chestNo: 337, name: 'ASHMIL MUHAMMED K', group: 'GRP-C', points: 7 },
    third: { studentId: 'c6-b-3', chestNo: 225, name: 'MUHAMMED FARHAN K', group: 'GRP-A', points: 5 },
  },
  'evt-9': {
    eventId: 'evt-9',
    publishedAt: '2026-08-09T17:30:00Z',
    first: { studentId: 'c10-b-3', chestNo: 301, name: 'MUHAMMED SAHAL M', group: 'GRP-C', points: 15 },
    second: { studentId: 'c9-b-2', chestNo: 102, name: 'MUHAMMED SHAYAN MK', group: 'GRP-B', points: 10 },
    third: { studentId: 'c10-b-1', chestNo: 201, name: 'MUHAMMED AMEEN M', group: 'GRP-A', points: 5 },
  },
};
